/*! ----------------------------------------------------------------------------
 * @file    example_selection.h
 * @brief   Example selection is configured here
 *
 * @attention
 *
 * Copyright 2013 - 2020(c) Decawave Ltd, Dublin, Ireland.
 *
 * All rights reserved.
 *
 */

#ifndef TEST_SELECTION_
#define TEST_SELECTION_

#ifdef __cplusplus
extern "C" {
#endif

//Enable the needed example/test. Please enable only one example/test!

//#define SIMPLE_TX_CP
//#define SIMPLE_RX_CP

//#define TEST_SIMPLE_TX
//#define TEST_SIMPLE_RX

//#define TEST_READING_DEV_ID
//#define TEST_SIMPLE_TX_PDOA
//#define TEST_TX_SLEEP
//#define TEST_TX_SLEEP_IDLE_RC
//#define TEST_TX_SLEEP_AUTO
//#define TEST_TX_SLEEP_TIMED
//#define TEST_TX_WITH_CCA


//#define TEST_RX_DIAG
//#define TEST_RX_SNIFF
//#define TEST_RX_TRIM
//#define TEST_SIMPLE_RX_PDOA

//#define TEST_SIMPLE_TX_STS_SDC
//#define TEST_SIMPLE_RX_STS_SDC

//#define TEST_SIMPLE_TX_AES
//#define TEST_SIMPLE_RX_AES

//#define TEST_TX_WAIT_RESP
//#define TEST_TX_WAIT_RESP_INT
//#define TEST_RX_SEND_RESP

//#define TEST_CONTINUOUS_WAVE
//#define TEST_CONTINUOUS_FRAME

//#define TEST_DS_TWR_INITIATOR_STS
//#define TEST_DS_TWR_RESPONDER_STS

//#define TEST_DS_TWR_INITIATOR

//#define TEST_DS_TWR_INITIATOR_CP
//#define TEST_DS_TWR_RESPONDER

//#define TEST_DS_TWR_RESPONDER_CP


//#define TEST_DS_TWR_STS_SDC_INITIATOR
//#define TEST_DS_TWR_STS_SDC_RESPONDER

//#define TEST_SS_TWR_INITIATOR
//#define TEST_SS_TWR_RESPONDER

//#define TEST_SS_TWR_INITIATOR_STS
//#define TEST_SS_TWR_RESPONDER_STS

//#define TEST_SS_TWR_INITIATOR_STS_NO_DATA
//#define TEST_SS_TWR_RESPONDER_STS_NO_DATA

//#define TEST_AES_SS_TWR_INITIATOR
//#define TEST_AES_SS_TWR_RESPONDER

//#define TEST_ACK_DATA_TX
//#define TEST_ACK_DATA_RX

//#define TEST_ACK_DATA_RX_DBL_BUFF

//#define TEST_SPI_CRC
//#define TEST_GPIO

//#define TEST_OTP_WRITE

//#define TEST_LE_PEND_TX
//#define TEST_LE_PEND_RX

//#define TEST_FRAME_FILTERING_TX
//#define TEST_FRAME_FILTERING_RX

//#define TEST_DS_TWR_STS_SDC_INITIATOR_AOA
//#define TEST_DS_TWR_STS_SDC_RESPONDER_AOA

//#define LOCALIZATION_DS_TWR_INIT
//#define LOCALIZATION_DS_TWR_RESP

//#define RTLS_SIMPLE_TX_PDOA
//#define AoA_rtls_tx
//#define AoA_rtls_rx

//#define AoA_RTLS_TX_AI
//#define AoA_RTLS_RX_AI

//#define AoA_rtls_rx_spi
//#define TEST_SIMPLE_TX_SPI
//#define AoD

//#define UART_TEST
//#define TEST_RX_DIAG_CP

//#define AoA_rtls_tx_txt
//#define AoA_rtls_rx_txt

//#define AoA_rtls_tx_two
//#define AoA_rtls_rx_two


//#define DS_TWR_INITIATOR_FINAL
//#define DS_TWR_RESPONDER_FINAL

//#define DS_TWR_INITIATOR_ORIGIN
//#define DS_TWR_RESPONDER_ORIGIN

//#define DS_TWR_INITIATOR_PACKET_SIMULATION
//#define DS_TWR_RESPONDER_PACKET_SIMULATION

//#define CUSTOM_DS_TWR_INITIATOR_WITH_NO_STS
//#define CUSTOM_DS_TWR_RESPONDER_WITH_NO_STS

//#define CUSTOM_DS_TWR_INITIATOR_WITH_NO_STS_2
//#define CUSTOM_DS_TWR_RESPONDER_WITH_NO_STS_2

//#define CUSTOM_DS_TWR_INITIATOR_WITH_NO_STS_3
//#define CUSTOM_DS_TWR_RESPONDER_WITH_NO_STS_3

//#define CUSTOM_DS_TWR_INITIATOR_WITH_NO_STS_4
//#define CUSTOM_DS_TWR_RESPONDER_WITH_NO_STS_4

//#define CUSTOM_DS_TWR_INITIATOR_WITH_NO_STS_5
//#define CUSTOM_DS_TWR_RESPONDER_WITH_NO_STS_5

//#define CUSTOM_DS_TWR_INITIATOR_WITH_NO_STS_ORIGIN
//#define CUSTOM_DS_TWR_RESPONDER_WITH_NO_STS_ORIGIN


//#define CUSTOM_DS_TWR_INITIATOR_TRIM
//#define CUSTOM_DS_TWR_RESPONDER_TRIM

//#define CUSTOM_DS_TWR_INITIATOR_CIR
//#define CUSTOM_DS_TWR_RESPONDER_CIR

//#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_2
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_3


//#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY_NO_DELAY
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1_NO_DELAY
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_2_NO_DELAY
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_3_NO_DELAY
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_4_NO_DELAY

//#define CUSTOM_DS_TWR_INITIATOR_MULTI_FREQUENCY
//#define CUSTOM_DS_TWR_RESPONDER_MULTI_FREQUENCY_ANCHOR1
//#define CUSTOM_DS_TWR_RESPONDER_MULTI_FREQUENCY_ANCHOR2

//#define CUSTOM_DS_TWR_INITIATOR_CHANNEL_SWITCHING
//#define CUSTOM_DS_TWR_RESPONDER_CHANNEL_SWITCHING
//#define CUSTOM_DS_TWR_RESPONDER_CHANNEL_SWITCHING_V2

//#define CUSTOM_DS_TWR_INITIATOR_WITH_STS
//#define CUSTOM_DS_TWR_RESPONDER_WITH_STS

//#define CUSTOM_DS_TWR_INITIATOR_WITH_STS_2
//#define CUSTOM_DS_TWR_RESPONDER_WITH_STS_2

//#define CUSTOM_DS_TWR_INITIATOR_MULTI_CIR_DATA
//#define CUSTOM_DS_TWR_RESPONDER_MULTI_CIR_DATA

//#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY_1VS1
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1VS1

//#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY_1VS2
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1_1VS2
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_2_1VS2

//#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_2
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_3

//#define CUSTOM_DS_TWR_INITIATOR_MULTI_FREQUENCY_1VS1
//#define CUSTOM_DS_TWR_RESPONDER_MULTI_FREQUENCY_ANCHOR_1VS1

#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY_1VS4
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1_1VS4
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_2_1VS4
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_3_1VS4
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_4_1VS4

//#define CUSTOM_DS_TWR_INITIATOR_SINGLE_FREQUENCY_1VS4_COMPARE
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_1_1VS4_COMPARE
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_2_1VS4_COMPARE
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_3_1VS4_COMPARE
//#define CUSTOM_DS_TWR_RESPONDER_SINGLE_FREQUENCY_ANCHOR_4_1VS4_COMPARE



#ifdef __cplusplus
}
#endif


#endif